/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
 * Generated on: 04-Jun-2022 10:14:03
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 16
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "arm_math.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Software\Matlab\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 16;
const float32_t B[16] = {
   -0.00347127649,-0.004851203877,-0.004245630931, 0.008891030215,  0.04423731565,
     0.1002331078,   0.1601002812,   0.1991063803,   0.1991063803,   0.1601002812,
     0.1002331078,  0.04423731565, 0.008891030215,-0.004245630931,-0.004851203877,
   -0.00347127649
};
